// compiled js file

// VARIABLES START
// Plot Type
const plotElem = {
    type: [
        "one-shot",
        "vignette",
        "line",
        "arc",
        "convergence",
        "divergence",
        "swansong",
        "module",
        "recurrence"
    ],
    tone: [
        "an aggressive",
        "a goofy",
        "a grim",
        "a happy",
        "an ironic/satiric",
        "an opportunist",
        "a philanthropic",
        "a sad",
        "a serious",
        "a tragic",
        "a whimsical",
        "a witty"
    ],
    genre: [
        "action",
        "celebration",
        "comedy",
        "crime",
        "drama",
        "heist",
        "historical",
        "horror",
        "instructional",
        "investigation",
        "mind-bender",
        "mission",
        "musical",
        "mystery",
        "negotiation",
        "patriotic",
        "philosophical",
        "political",
        "rivalry/competition",
        "romance",
        "satire",
        "supernatural",
        "thriller"      
    ]
}

// Fetch Quest, Rumors
const property = [
    // Ace-10 of spades from MHoF
    "used to belong to a famous general",
    "was blessed by the gods",
    "was used to kill someone important",
    "played a key role in changing fate",
    "everyone hates",
    "is a vital clue in an ongoing mystery or investigation",
    "has become corrupted",
    "hurts people",

    // from the Meme Machine
    "contains ancient secrets",
    "is absolutely useless",
    "is full of dirt",
    "was cursed by a witch",
    "is deeply and incredibly cursed",
    "used to be green",
    "has eyes",
    "looks like a goose",
    "someone left on a boat",
    "was lost at sea",
    "will fix my marriage",
    "can heal any wound",
    "is made of gold",
    "went missing years ago",
    "is hot to the touch",
    "is cold to the touch",
    "was stolen by bandits",
    "was created as a result of a fae deal gone wrong"
];

// Fetch Quest, Adventure Generator
const quest = {
    motivation: [
        // Ace-10 of spades from MHoF
        "so that they can settle a grudge",
        "because it will provide them with strength in the coming days",
        "because they are duty-bound to honor an agreement",
        "so that they can take down one of their enemies",
        "to tip the scales in their favor and gain the upper hand in an ongoing conflict",
        "so that they can kick someone's ass",
        "for Scooby Doo reasons",
        "as a means to depose someone in power",
        "because it's technically their job",
        "because it will help them achieve one of their goals",
    
        // from the Meme Machine
        "so that they can return it before anyone notices that it's gone",
        "even though they won't get paid",
        "because they're destined to have it",
        "so that they can buy new farmlands",
        "so that they can get paid for once",
        "and have been ever since it was lost at sea",
        "because someone asked really really nicely",
        "because one of them made a pinky promise to a witch",
        "so they can put it on display and go 'heehee' every time they look at it",
        "so they can get out of jury duty",
        "so they can get out of community service",
        "because they are hiding from several ghosts",
        "for comedy purposes",
        "so that someone can get laid",
        "because they need to make a little lad dance for them and he won't do it without the proper incentive",
        "so that they won't be executed by royalty",
        "because they need angsty backstory motivation",
        "so that they can frame someone",
        "because they'll be killed if they don't",
        "to make someone's wife happy",
    
        // adventure seed generator
        "because they are poor",
        "because they want to gain respect",
        "because nobody else was doing it and it looked like it needed to be done",
        "because they want to commit mass murder of a nearby sttlement",
        "because they quest to fulfill a prophecy",
        "because they have been lied to",
        "because they think it would save the world",
        "because they are actually gods",
        "because they are bored",
        "because a vision told them so",
        "for greater good",
        "because they are demigods and want to ascend",
        "because their leader has recurring dreams about it",
        "because they have run out of native unstable individuals to capture",
        "because they serve an elder evil god",
        "because they are afraid of their master",
        "because they want to leave a legacy of suffering",
        "because they can't stand watching others be happy and at peace",
        "because they are double agents",
        "because of blackmail",
        "because they want to ruin the lands of an enemy",
        "because they want to become famous",
        "because they wish to escape to another world",
        "because they need a new home",
        "because if they don't they will be executed",
        "because they need a new food source",
        "because they are afflicted with a curse",
        "because they are sabateurs for a foreign power",
        "because they want to start a war",
        "because they were groomed for this since childhood",
        "to gain glory in the afterlife",
        "because they serve a demon lord",
        "because they wish to unleash the titans",
        "because of peer pressure",
        "to achieve communion with a spiritual manifestation outside of this world",
        "because they want to get rich",
        "because they conspire to overthrow the King",
        "because they want to control trade of a certain good",
        "because they want to cause a mass extinction event",
        "because they quest to recover a lost technology or form of magic",
        "because it's how they get joy",
        "because they are misguided",
        "because they want to activate nearby volacanoes",
        "because they seek to rule the world",
        "because they were wronged and want revenge",
        "because they are tired of being the ones to come in last",
        "because they are selfish and unable to comprehend other's suffering",
        "because they want to leave a lasting impression to the world",
        "because they want to make the world better for their progeny",
        "because they want to offer this world to older evils",
        "because they want to resurrect an ancient evil",
        "because they seek immortality",
        "because the prophecy demanded it",
        "because they are desperate",
        "because of the enemy, which no one can remember why they hate each other anymore",
        "because they are heartbroken their beloved leader was slain",
        "because they believe the only way to save a corrupt world is through corruption",
        "because they want to be remembered forever",
        "because they were lied to",
        "because they were offended",
        "because they want to become powerful",
        "because they want to free their people",
        "because they want to upset the status quo",
        "because they desire it above all else",
        "because they are rebels fighting an oppressive power",
        "because they serve a devil prince",
        "because their friends and family are at risk",
        "to fund their search for personal immortality",
        "because they are tired of the suffering",
        "for love",
        "to make their cause better known",
        "because they have been driven mad by nightmares",
        "because magic warped them to do evil",
        "because they want to find kidnapped royalty",
        "because they need to escape oppression",
        "because they gave a promise to a dying mentor",
        "because they want to get revenge",
        "because they were ordered to",
        "because they are secretly part of 'the first'; the first group of humanoid to exist",
        "because they want to start an eternal fight",
        "because cruelty inflicted by others causes them to hate, hate, hate",
        "because they are getting paid",
        "because they want to harm their (innocent) enemy",
        "because they are cursed and doomed to die",
        "because of the failure of their previous plot to (roll motivation again)",
        "because they are dying of an unknown disease",
        "because they seek to boil off the oceans",
        "because they serve an evil master from another dimension",
        "because they want to destroy a god",
        "because they want to wipe out a race",
        "because it is their divine right",
        "because they are above the law",
        "because they are jilted",
        "because they are afraid",
        "because they misread a passage in a book",
        "because they want to avange their lost ones",
        "because they want to rectify a perceived insult",
        "because they seek redemption",
        "because they want to prevent a plague from spreading",
        "because their families are suffering",
        "because it's required for membership in the elite club",
        "because their leader hears voices",
        "because they lost a bet to a big bad guy",
        "because they have crushing debts",
        "because it will bring about the revolution",
        "because they feel responsible",
        "because they feel guilty",
        "because the world is corrupt",
        "because of sacred honor",
        "because of unfairness",
        "because it will restore balance",
        "because the abomination must be stopped",
        "because the world deserves it",
        "because the innocent have suffered enough",
        "because corruption must end",
        "because they fear the darkness ahead",
        "because rent is too damn high",
        "because a mage ordered it",
        "because the ends justify the means",
        "mostly because they can",
        "so as to soothe their guilty conscience",
        "because they are dissatisfied with current trends",
        "because they are jealous of their rivals' success",
        "because they are afraid to be forgotten",
        "because they thought it was easy and needed the money",
        "because it would fulfill part of the prophecy",
        "because the process stated it must be done",
        "because they want to be different than the rest",
        "because they are under a powerful geas spell from an evil wizard",
    ],
    twist: [
        // Ace-10 of spades from MHoF
        "this is the perfect opportunity for one of them to take vengeance",
        "the upcoming choices should not be made by one person alone",
        "victory will come at great cost and sacrifice",
        "they don't have all of the information",
        "there's a good chance that they will be attacked by a werewolf",
        "they need to be careful not to piss anybody off otherwise they WILL be having an afternoon tea party with the Barristers (aka die horribly)",
        "they are liable for their own actions and have no one to blame for the consequences but theirselves",
        "however bad they think this adventure is going to be, it is going to be WAY worse. Like way worse. Oh my god",
        "while they may accomplish their goals, there is a good chance that they will lose sight of what is most important in the process",
    
        // from the Meme Machine
        "the real treasure will NOT be the friends that they made along the way",
        "hey, it might be fun anyways",
        "surely nothing could possibly go wrong :)",
        "they're not the only ones looking for it",
        "surely things can't get any worse than this! Spoiler alert: they can",
        "wait! There's more",
        "this might get us executed by royalty",
        "it gets worse",
        "this might be funny",
    
        // fantasy generator - note
        "someone involved has long longed for something more",
        "someone involved has a grudge to settle",
        "someone involved has a reputation to salvage",
        "someone involved has to atone for a past misdeed",
        "someone involved has a secret that musn't be revealed",
        "someone involved is in denial about something important",
        "someone involved is often in the wrong place at the wrong time",
        "someone involved has recently lost someone dear",
        "someone involved owes a debt to someone powerful",
        "someone involved can't return home for a certain reason",
        "someone involved is pursuing someone else",
        "someone involved failed to protect someone once",
        "someone involved will make a mistake that will change everything",
        "not all is as it first appears",
        "someone involved will lose a limb in a horrific manner",
        "an important reunion will go horribly off the rails",
        "someone involved will harbor a hidden agenda the entire time",
        "the old are not wise in this story",
        "someone involved is still haunted by a past mistake",
        "there have been whispers for a while that something is not right with the royal family",
        "the ancient sword they discovered will turn out to be junk",
        "an important prophecy will be delivered by a seer with a reputation for exaggeration",
        "someone involved has a lot of hard lessons to learn",
        "the gods cannot be trusted",
    
        // fantasy generator - twist
        "a rival was an ally all along",
        "someone who was thought to be dead will return in the flesh",
        "all the characters are animals",
        "the prophecy will not come true",
        "this story will have an unhappy ending",
        "the villain will escape at the end of this story",
        "this will turn out to be a red herring",
    
        //adventure seed generator
        "they botched the formula",
        "they have been lied to",
        "their allies are only passively helping",
        "they do not know who to trust",
        "they have been poisoned",
        "one of them is a traitor",
        "the person funding them has called in their debt",
        "they are betrayed by one of their own",
        "one of them is captured",
        "one of them is arrested",
        "they got false information",
        "they have angered a divinity",
        "fear has gripped their hearts",
        "they are too reckless — taking wanton violence as the answer to anything that is not exclusively off limits",
        "a traitor is about to betray them",
        "a disease is wiping them out",
        "their plan is in shreds",
        "the odds are stacked against them",
        "they have lost their trump card",
        "they are cursed",
        "they are losing hope and are about to give up",
        "they are runnnig amok",
        "they have become unstable, and don't know it",
        "they just recently escaped being prisoners and do not have as many resources as they are used to",
        "they have been overly taxed and do not have as many resources as they are used to",
        "there is a spy in their midst",
        "they are also fighting another enemy on a separate front",
        "they fell into a trap",
        "they have lost the instructions",
        "their emotions will lead them astray",
        "they don't really want to do it",
        "their enemies are ahead of them",
        "the area is surrounded by enemy forces",
        "they don't seem to be the only group interested in this",
        "no one will believe them",
        "their leadership is incompetent",
        "time is running out",
        "an alarm has been triggered",
        "they don't know they are sleeper agents, about to activate",
        "they have not gathered all the necessary pieces",
        "they don't know they have already been compromised",
        "they have based their plans on erroneous information",
        "a god opposes them",
        "they have been ambushed twice already",
        "they are underestimating their oppposition",
        "they have to face another, more powerful enemy after conquering the first",
        "they find out that their victory would cause harm to innocents",
        "they must form an uneasy alliance with the enemy to be able to face a new adversary",
        "they are too cautious, taking twice as long to make a move than necessary",
        "they got squeamish",
        "they discover that their old mentor has turned against them - and for all the right reasons",
        "they lack an important resource",
        "they have caught a terrible disease",
        "they lost their map",
        "their numbers are dwindling",
        "they are all dying",
        "a destructive device has been hidden in the area",
        "they don't know that they are simply pawns in a bigger game",
        "they must wait until nighttime to act",
        "their retreat is cut off behind them",
        "they squabble",
        "they have lost their leader",
        "a new invention threatens their plans",
        "discover that by succeeding they would lose something important",
        "finally understand that their actions have harmed themselves",
        "they lost contact with their support network",
        "there is a supernatural presence at the site",
        "their alliances are beginning to falter",
        "ghosts have targeted them",
        "components are expensive",
        "their magic is failing",
        "it has become painful to walk in sunlight",
        "the seasons are changing",
        "it is unstable",
        "the villain will soon try to stop them",
        "they are a week early",
        "they aren't the only ones",
        "authorities are quickly approaching",
        "they have underestimated the difficulty involved",
        "they are running out of time",
        "they are not the only ones with the same goals",
        "a fire has broken out",
        "the flood waters are rising",
        "the key is lost",
        "they are losing support",
        "the most unexpected source has just brought them the missing component",
        "they are offered a bribe for abandoning their plans",
        "a surprise visitor changes the situation",
        "they start to believe that they have lost some of their sanity",
        "they understand that they no longer can trust their senses",
        "they believe too soon that they have succeeded",
        "they are flanked on all sides",
        "a natural disaster is coming",
        "an enemy horde is rushing in",
        "the public opinion is against them",
        "the stars aren't right yet",
        "they follow a false prophecy",
        "one of their own died too early",
        "they haven't found the right sacrifice",
        "they are still searching for the right place",
        "a natural disaster occurs",
        "rivals have beat them to it",
        "the creatures escape",
        "they are foiled by their own pride",
        "everyone likes the new state of affairs better",
        "someone is suspiscious of the head elder"
    ],
    place: [
        // adventure seed generator
        "on the border",
        "atop a mesa of volcanic glass",
        "at the bottom of a maze",
        "at an ancient stone henge",
        "in a refugee camp",
        "at the crossroads at a new moon midnight",
        "beside an old church",
        "at the top of the waterfalls",
        "across the sea",
        "near a cursed village",
        "in a field",
        "inside the skull of a dead god",
        "in plain sight",
        "at the witches' coven",
        "at a fortress under siege",
        "in a cave",
        "because they've been cursed by a priest of an ancient one",
        "in a druid's grove",
        "near a magical spring",
        "on top of a mountain",
        "at the top of a waterfall",
        "at the bottom of a waterfall",
        "at a bridge",
        "at the dragon's lair",
        "at the ruins of a village that was fine the last time you saw it",
        "at the kingdom treasury",
        "in infected swamps",
        "at an arena with an event in progress",
        "in a local cave that connects to underdark",
        "in the throne room",
        "in the library",
        "in a leper colony",
        "inside the volcano",
        "at the empire's capital",
        "in a local church",
        "at a mass grave",
        "at a four-day alcohol-fueled jousting competition",
        "at the bottom of the sea",
        "at the center of town",
        "at the shores before the world's end",
        "at a performance",
        "at the crack of dawn",
        "at the crypt of a wizard",
        "at the burial mounds of the ancient prison",
        "at a mage's tower",
        "at the castle in the sky",
        "at the edge of reality",
        "at a wizard's home",
        "in the sewers",
        "at the caves under the mountain",
        "at a hive for giant bees",
        "at a lonely lighthouse",
        "along the highway",
        "at the end of the world",
        "at the old war monument",
        "at a dimensional nexus",
        "at the top of a mountain",
        "at a god's home",
        "inside the inner chambers",
        "outside the palace walls",
        "at a VIP wedding ceremony",
        "by the King's road",
        "at the center under the darkest clouds",
        "at the gates to the divine path",
        "at the catacombs",
        "in the midst of a riot",
        "at the kingdom armory",
        "on a busy road",
        "beneath a bridge",
        "in a graveyard",
        "behind a waterfall",
        "between two dimensional vortexes",
        "at the center of a former battlefield",
        "at the eye of a stationary storm",
        "in a flying fortress",
        "outside the town",
        "at the forbidden section of a mage's library",
        "up a tree",
        "at the center of the dam",
        "in the castle courtyard",
        "at the center of an active battlefield",
        "during the festival",
        "in a town afflicted with the plague",
        "at a bizarre menagerie",
        "amongst a crowd",
        "at the royal family's tomb",
        "at the guildhall",
        "at the moment the seas part before them",
        "on a storm-damaged ship",
        "at the mysterious portal recently found",
        "at the feet of the sleeping titans",
        "at the noble's gathering",
        "at a grand celebration",
        "in the hull of a ship",
        "under the druid's grove",
        "in the tombs and catacombs of a large temple",
        "in the catacombs",
        "in the necropolis",
        "among the tombs of giants",
        "on the lowest level of The Mad Wizard's dungeon",
        "in the Tower of Light",
        "in the Far Ethereal Plane",
        "on an island in the Astral Sea",
        "in the Tower of Darkness",
        "in the barrow-downs",
        "at a menhir circle",
        "in the mountains",
        "in the deset",
        "in the plains",
        "at the river",
        "in the cathedral",
        "in a mine",
        "at the end of the rainbow",
        "in a glacial fortress",
        "in a flying castle",
        "on a swimming city",
        "in a canyon",
        "near a volcano",
        "in a month",
        "in three days",
        "in a secret facility",
        "in the city center",
        "in the museum",
        "at the town hall",
        "in the gaming rooms",
        "in the casinos",
        "at the card tables",
        "on the highways",
        "in the prison",
        "in the dungeons"
    ]
}

// NPC Builder, Rumors, Adventure Generator
const chara = {
    chara: [
        "a peasant girl",
        "a peasant boy",
        "a young boy",
        "a young girl",
        "a lad",
        "a lass",
        "a fruit-seller",
        "a gem merchant",
        "a sellsword",
        "a nomad",
        "a knight",
        "an assassin",
        "a gentleman thief",
        "a gentlewoman thief",
        "a soldier",
        "a monk",
        "a sorceror",
        "an enchanter",
        "a witch",
        "a warlock",
        "a warrior",
        "a mage",
        "an outlaw",
        "a ruffian",
        "a brigand",
        "a pickpocket",
        "a thief",
        "a woodsman",
        "a warlord",
        "a page",
        "a squire",
        "a troubadour",
        "an empress",
        "an emperor",
        "a noblewoman",
        "a nobleman",
        "a lord",
        "a lady",
        "a prince",
        "a princess",
        "a diplomat",
        "a monsterologist",
        "a swordmaster",
        "an apprentice",
        "an assassin-in-training",
        "an enchantress-in-training",
        "a summoner-in-training",
        "a witch-in-training",
        "a necromancer-in-training",
        "a prophet-in-training",
        "a sorceror-in-training",
        "an ogre",
        "a dragon",
        "a centaur",
        "a charlatan",
        "a vampire",
        "a genie",
        "a troll",
    
        // races from the myth book
        "a dale elf",
        "a deep elf",
        "a dwarf",
        "a goblin",
        "a half elf",
        "a high elf",
        "a human",
        "a suhk",
        "a wildren",
    
        // classes from the myth book
        "an alchemist",
        "an artificer",
        "a bard",
        "a cleric",
        "a druid",
        "a fighter",
        "a paladin",
        "a ranger",
        "a rogue",
        "a runesmith",
        "a wizard",
    
        // professions from the myth book
        "a coalescer",
        "an excavator",
        "a harvester",
        "a logger",
        "a skinner",
        "a farmer",
        "a hunter",
        "a lumberjack",
        "a miner",
        "a panner",
        "a butcher",
        "a carpenter",
        "a gemcutter",
        "a glassmaker",
        "a papermaker",
        "a smelter",
        "a tanner",
        "a weaver",
        "an architect",
        "a blacksmith",
        "a brewer",
        "a chef",
        "a glassblower",
        "a lapidary",
        "a leatherworker",
        "a tailor",
        "a trapmaker",
        "a woodworker",
        "an appraiser",
        "a laborer",
        "a mender",
    
        // from the Meme Machine
        "an eccentric candyman",
        "a retail employee",
        "a werewolf",
        "a feral child",
        "a snake-oil salesman",
        "an influencer",
        "a cowboy",
        "a pirate",
        "a rat",
        "a child psychologist",
        "a ghost-hunter",
        "an archivist",
        "a creature",
        "a demolitions expert",
        "a goose",
        "a duelist",
        "a dog",
        "a construct",
        "a landlord",
        "a celebrity chef",
        "the village idiot",
        "some old guy",
        "some old lady",
        "a tax-evader",
        "a draft dodger",
        "a pyrotechnician",
        "an arsonist",
        "a professional arsonist",
        "a retired assassin",
        "a goth",
        "a clown",
        "an entire circus of clowns",
        "three possums in a trench coat",
        "a doctor",
        "a lawyer",
        "a con artist",
        "a grifter",
        "a little lad in a fancy suit",
        "a hot girl",
        "a hot guy",
        "a hot person",
        "a malewife",
        "an entity",
        "an absent father",
        "a war criminal",
        "a shitty wizard",
        "a conspiracy theorist",
        "an adrenaline junkie",
        "a time traveler",
        "an Italian",
        "an asshole",
        "a deadbeat dad",
        "a deadbeat mom",
        "a deadbeat parent",
        "a Little League coach",
        "a mobster",
        "a grad student",
        "a librarian",
        "a researcher",
        "a research assistant",
        "an entomologist",
        "a butch lesbian",
        "a dancer",
        "a singer",
        "a musician",
        "a historian",
        "a private investigator",
        "a detective",
        "a comedian",
        "someone",
        "a pro-wrestler",
        "a furry"
    ],
    adjective: [
        "a peasant",
        "a young",
        "a young",
        "a fruit-selling",        
        "a gentleman",
        "a gentlewoman",
        "an apprentice",
        "a charlatan",
        "a vampire",

        // races from the myth book
        "a dale elf",
        "a deep elf",
        "a dwarf",
        "a goblin",
        "a half elf",
        "a high elf",
        "a human",
        "a suhk",
        "a wildren",
    
        // from the Meme Machine
        "an eccentric",
        "a werewolf",
        "a feral",        
        "an influencer",
        "a child",
        "a celebrity",
        "the village idiot",
        "some old",
        "a tax-evading",
        "a draft-dodging",
        "a professional",
        "a retired",
        "a goth",        
        "a little",
        "a hot",
        "an absent",
        "a shitty",        
        "a time-traveling",
        "an Italian",
        "an asshole",
        "a deadbeat",        
        "a butch",
        "a dancing",
        "a singing",

        // adventure seed generator
        "a paramilitary",
        "a military",
        "a search",
        "a suicidal",
        "a fleeing",
        "an organized",
        "an insatiable",
        "a sickened",
        "a lusty",
        "a maniacal",
        "an unorganized",
        "a pugilistic",
        "a busybody",
        "an evil",
        "a sociopathic",
        "an underground",
        "a dying",
        "a benevolent",
        "an arsonistic",
        "a disorganized",
        "a convicted",
        "a noble",
        "a liar",
        "a chaotic",
        "a malicious",
        "a murderous",
        "a pugnacious",
        "a secret",
        "an elderly",
        "a violent",
        "an unharmonious",
        "a devious",
        "a young",
        "a surreptitious",
        "a quarelling",
        "an ideologically split",
        "a ragged",
        "a cursed",
        "a good",
        "an enlightened",
        "a zealous",
        "a heroic",
        "an amnesiac",
        "a resurrected",
        "a fey-touched",
        "an elite",
        "a lycanthropic",
        "an escaped",
        "an injured",
        "a commissioned",
        "an official",
        "a random",
        "a self-pitying",
        "a well-dressed",
        "a xenophobic",
        "a superstitious",
        "a drunk",
        "a depressive",
        "a morbid",
        "a mortally wounded",
        "a diseased",
        "a contrite",
        "a hateful",
        "an alcoholic",
        "a drug-addicted",
        "a fanatical",
        "a homeless",
        "a confused",
        "an artistic",
        "a desperate",
        "a suspicious",
        "an unaccountable",
        "an exhausted",
        "a vocal",
        "an undead",
        "a shady",
        "a righteous",
        "a plaintive",
        "a cowardly",
        "an insane",
        "an unscrupulous",
        "an oppressed",
        "a conned",
        "a fallen",
        "an undercover",
        "a reluctant",
        "a bloodthirsty",
        "an otherworldly",
        "a celestial",
        "an outsider",
        "an insectoid",
        "a brilliant",
        "a greedy",
        "a materialistic",
        "an unholy",
        "an ancient",
        "an obsessive",
        "an old",
        "a sole",
        "an outgrown",
        "a renowned",
        "a rich",
        "a poor",
        "a reformed",
        "a secretive",
        "a paranoid",
        "a compulsive",
        "a perverse",
        "an iconoclastic",
        "a nihilistic",
        "a former",
        "an underappreciated",
        "a kindly",
        "a unique"
    ],
    noun: [
        "girl",
        "boy",
        "lad",
        "lass",
        "fruit-seller",
        "gem merchant",
        "sellsword",
        "nomad",
        "knight",
        "assassin",
        "thief",
        "soldier",
        "monk",
        "sorceror",
        "enchanter",
        "witch",
        "warlock",
        "warrior",
        "mage",
        "outlaw",
        "ruffian",
        "brigand",
        "pickpocket",
        "woodsman",
        "warlord",
        "page",
        "squire",
        "troubadour",
        "empress",
        "emperor",
        "noblewoman",
        "nobleman",
        "lord",
        "lady",
        "prince",
        "princess",
        "diplomat",
        "monsterologist",
        "swordmaster",
        "apprentice",
        "assassin-in-training",
        "enchantress-in-training",
        "summoner-in-training",
        "witch-in-training",
        "necromancer-in-training",
        "prophet-in-training",
        "sorceror-in-training",
        "ogre",
        "dragon",
        "centaur",
        "vampire",
        "genie",
        "troll",
        
        // classes from the myth book
        "alchemist",
        "artificer",
        "bard",
        "cleric",
        "druid",
        "fighter",
        "paladin",
        "ranger",
        "rogue",
        "runesmith",
        "wizard",

        // professions from the myth book
        "coalescer",
        "excavator",
        "harvester",
        "logger",
        "skinner",
        "farmer",
        "hunter",
        "lumberjack",
        "miner",
        "panner",
        "butcher",
        "carpenter",
        "gemcutter",
        "glassmaker",
        "papermaker",
        "smelter",
        "tanner",
        "weaver",
        "architect",
        "blacksmith",
        "brewer",
        "chef",
        "glassblower",
        "lapidary",
        "leatherworker",
        "tailor",
        "trapmaker",
        "woodworker",
        "appraiser",
        "laborer",
        "mender",

        // from the Meme Machine
        "candyman",
        "a retail employee",
        "child",
        "snake-oil salesman",
        "cowboy",
        "pirate",
        "rat",
        "psychologist",
        "ghost-hunter",
        "archivist",
        "creature",
        "demolitions expert",
        "goose",
        "duelist",
        "dog",
        "construct",
        "landlord",
        "guy",
        "pyrotechnician",
        "arsonist",
        "assassin",
        "clown",
        "doctor",
        "lawyer",
        "con artist",
        "grifter",
        "lad in a fancy suit",
        "person",
        "malewife",
        "entity",
        "father",
        "mother",
        "war criminal",
        "conspiracy theorist",
        "adrenaline junkie",
        "time traveler",
        "asshole",
        "dad",
        "mom",
        "parent",
        "Little League coach",
        "mobster",
        "grad student",
        "librarian",
        "researcher",
        "research assistant",
        "entomologist",
        "lesbian",
        "dancer",
        "singer",
        "musician",
        "historian",
        "private investigator",
        "detective",
        "comedian",
        "a pro-wrestler",
        "a furry"
    ],
    trait: [
        "can be restless",
        "can be ambitious",
        "is kind",
        "used to be idealistic",
        "is past prime",
        "can be brusque",
        "is stubborn to a fault",
        "has not laughed in a long time",
        "lies more often than not",
        "is surprisingly gentle",
        "once was hopeful",
        "can be independently-minded",
        "can be selfish",
        "can be sharp",
        "can be over-critical",
        "tends to be reckless",
        "is abrasive",
        "has become aimless",
        "has a lot of defense mechanisms",
        "can be cold",
        "has a tendency to be cowardly",
        "is destructive",
        "can be detached",
        "can be judgemental",
        "has a sense of humor",
        "has a reputation for being melodramatic",
        "has burnt every bridge",
        "can be vain",
        "has become withdrawn",
        "is taciturn",
        "can be stoic",
        "is suave",
        "is quick-witted",
        "no longer has any loyalties",
        "has a strong moral compass",
        "has 99 problems, and a sidekick is one of them",
        "is a crank",
        "has a reputation for being eccentric",
        "is misunderstood",
        "is a worrywart",
        "is innocent",
        "is rather unpredictable",
        "is unexpectedly charismatic",
        "has a poker face",
        "is soft-hearted",
        "can be independently-minded",
        "used to be selfish",
        "has many controversial opinions",
        "is deadpan",
        "can be pretentious",
        "is prim",
        "is puritanical",
        "can be tactless",
        "tends to attract trouble",
        "is blind",
        "thrives on drama",
        "can be forgetful",
        "is a drifter",
        "is a chatterbox",
        "is spineless",
        "is rather incompetent",
        "is bright",
        "is sensible to a fault",
        "is a forgiving soul",
        "is braver than most",
        "has no moral code",
        "has run away",
        "is affable",
        "is taciturn",
        "is overly polite",
        "can be naïve",
        "can be overly pompous",
        "is overly adventurous",
        "is a lover of books",
        
        // from the Meme Machine
        "was found by the side of the road",
        "is haunted",
        "is hot",
        "is divorced",
        "is bisexual",
        "is goth",
        "is evil",
        "is stinky",
        "is nonbinary",
        "is literally neurodivergent and a minor",
        "is a furry",
        "is a flat earther",
        "is a flat earther to be a dick",
        "is a bit of a daredevil",
        "is an arsonist",
        "is an alcoholic",
        "is so hungover",
        "is so close to snapping",
        "is terrified of ducks",
        "is really up their own ass about poetry",
        "is currently facing a lawsuit",
        "is currently running a scam",
        "is banned from Applebee's",
        "is plagued by visions",
        "is blue for no reason",
        "is reasonably horny",
        "is unreasonably horny",
        "is from hell",
        "is from the LARP equivalent of Texas",
        "is afraid of the dark",
        "is a competitive little shit",
        "has a headache",
        "has a fat ass",
        "has a cool hat",
        "has a child nemesis",
        "has a tiny creature for a sidekick",
        "has a penchant for truly terrible wordplay",
        "has no idea whats going on",
        "has not been around civilaztion for some time",
        "has not bathed in three weeks",
        "has the attention span of a goldfish",
        "has had their medical license revoked",
        "has already snapped",
        "has killed before and will kill again",
        "has got it going on",
        "has human eyes",
        "does not have human eyes",
        "has interesting feelings about spiders",
        "has three weed-smoking girlfriends",
        "has blue hair and pronouns",
        "has an ongoing feud with the local mage's guild (don't ask)",
        "only has one outfit",
        "thinks they're a goose",
        "thinks they're hot shit",
        "thinks your mom is hot",
        "thinks your dad is hot",
        "thinks your parent of unspecified gender is hot",
        "thinks the earth is shaped like a donut because it's funny",
        "thinks the earth is shaped like a donut because they're kind of hungry right now",
        "believes all rumors to be true",
        "doesn't talk to their parents",
        "doesn't believe in hell",
        "doesn't think the sun is real",
        "needs therapy",
        "needs a nap",
        "needs to get laid",
        "eats glue",
        "eats magic items",
        "smokes way too much weed",
        "smokes a regular amount of weed",
        "considers themself to be morally grey but has committed several murders",
        "will die on any hill",
        "won't shut up about their kids",
        "would survive a Saw trap",
        "loves arguing",
        "loves puppets",
        "loves soup",
        "loves their wife",
        "likes to break the fourth wall",
        "really likes dragons",
        "hates children",
        "acts like an anime character",
        "solves all of their problems with card games",     
        "regularly commits tax fraud",
        "used to be a war criminal and has since been pardoned",
        "lies about their age",
        "lies through the newspaper",
        "faked their death",
        "denies any and all responsibility for... the incident",
        "woke up and chose violence",
        "vapes",
        "fucks",
        "can be real dick",
        "naps in weird places",
        "got their ears pierced at Claire's",
        "wears way too much eyeliner",
        "went out for a pack of smokes and never returned",
        "took one philosophy class in university and won't shut up about it",
        "solves mysteries on the side",
        "is really passionate about saving the bees",
        "has their own fan club",
        "plays the violin",
        "plays the piano",
        "minds their own business",
        "loves to gossip"
    ],
    group: [
        // adventure seed generator
        "order",
        "horde",
        "clique",
        "gaggle",
        "mob",
        "collegium ",
        "armed group",
        "squad",
        "cadre",
        "trio",
        "duo",
        "quintet",
        "pack",
        "wandering troupe",
        "crime ring",
        "group",
        "cabal",
        "coven",
        "gang",
        "bunch",
        "fellowship",
        "posse",
        "school class",
        "syndicate",
        "delegation",
        "secret society",
        "guild",
        "extended family",
        "noble house",
        "platoon",
        "caravan",
        "sisterhood",
        "work team",
        "team",
        "association",
        "cartel",
        "club",
        "congregation",
        "gentlemen's club",
        "faction",
        "crew",
        "hidden society",
        "league",
        "converstation club",
        "religious sect",
        "tribe",
        "elite squad",
        "brotherhood",
        "charity organization",
        "support staff",
        "entourage",
        "assembly",
        "noble family",
        "governing body",
        "ensemble",
        "conclave",
        "coterie",
        "organization",
        "citizens",
        "circle",
        "partnership",
        "society",
        "party",
        "cult",
        "group",
        "troop",
        "army",
        "mass",
        "gathering",
        "political faction",
        "inbred family",
        "choir",
        "crowd",
        "splinter faction",
        "band",
        "conspiracy",
        "cult",
        "clan",
        "collegium",
        "patchwork",
        "network",
        "cell",
        "panel",
        "doomsday cult",
        "union",
        "collective",
        "circus"
    ],
    members: [
        // adventure seed generator
        "squires",
        "adventurers",
        "assassins",
        "fish people",
        "drunken farmers",
        "illusionists",
        "settlers",
        "werewolves",
        "raiders",
        "industrialists",
        "acolytes",
        "vampires",
        "collectors",
        "animals",
        "land surveyors",
        "rogues",
        "elementals",
        "goblin hunters",
        "lowlives",
        "knights",
        "mercenaries",
        "bardic actors",
        "plants",
        "nobles and their retinue",
        "royalty",
        "lepers",
        "kobold trapsmiths",
        "wizards",
        "ancients",
        "bandits",
        "mendicant monks",
        "giants",
        "prisoners",
        "dwarven archaeologists",
        "con artists",
        "alchemists",
        "thieving travelers",
        "villians",
        "slaves",
        "diplomats",
        "doppelgangers",
        "temple monks",
        "rebels",
        "runaways",
        "psychics",
        "tinkers",
        "local spirits",
        "masterless golems",
        "druids",
        "kings",
        "diviners",
        "travelling merchants",
        "mysterious cloaked men",
        "liches",
        "sprites",
        "traitors",
        "monitors",
        "scholars",
        "guards",
        "ousted monarchs",
        "ghosts",
        "militia members",
        "children",
        "orphan children",
        "fairies",
        "holy inquisitors",
        "singers",
        "enchanters",
        "enchantresses",
        "merchants",
        "cavaliers",
        "religious zealots",
        "mummers",
        "bards",
        "orcs",
        "dragons",
        "otherwordly beings",
        "dukes",
        "duchesses",
        "undead",
        "slavers",
        "escaped slaves",
        "witches",
        "planar travelers",
        "charity mission workers",
        "chaos worshippers",
        "monks",
        "priests",
        "pesants",
        "common folk",
        "terrorists",
        "defectors",
        "pageboys",
        "spies",
        "foreign diplomats",
        "nuns",
        "nomads",
        "plant creatures",
        "philosophers",
        "sea creatures",
        "pirates",
        "barons",
        "ladies",
        "teenagers",
        "unemployed tradespeople",
        "peasants",
        "aristocrats",
        "royals",
        "scientists",
        "necromancers",
        "gnomes",
        "masons",
        "painters",
        "senior villagers",
        "housebreakers",
        "fishermen",
        "vintners",
        "leatherworkers",
        "intelligentsia",
        "craftspersons",
        "convicts",
        "felons",
        "smiths",
        "homunculi",
        "golems",
        "bodysnatchers",
        "vivisectionists",
        "ax murderers",
        "tulip growers",
        "fey creatures",
        "barbarians",
        "scribes",
        "crime bosses",
        "drug lords",
        "brothel keepers",
        "veterans",
        "draftees",
        "deserters",
        "masters",
        "journeymen",
        "home owners",
        "shopkeepers",
        "smugglers",
        "corrupt politicians",
        "mages",
        "hags",
        "violent vigilantes"
    ]
}

// Rumors
const rumors = {
    source: [
        "My cousin's friend told him that",
        "My cousin's friend told her that",
        "My cousin told me that",
        "My friend overheard some patrons at the tavern talking about how",
        "I overheard one of the town guard saying that",
        "My friend heard that",
        "I overheard someone saying that",
        "A buddy of mine said that",
        "You didn't hear this from me, but",
        "Rumor has it that",
        "Don't quote me on this, but I heard that",
        "I don't know if this is true or not, but I heard that",
        "I heard through the grapevine that",
        "So get this — apparently",
        "A friend of mine was telling me the other day that",
        "A friend of a friend said that",
        "I read in the newspaper that",
        "The bartender slipped me a note that said that",
        "The bartender gave me a heads up that",
        "Someone gave me a heads up that",
        "The spirits revealed to me that",
        "Just trust me on this one, but",
        "The town busybody said that",
        "This might just be me being nosy, but",
        "I'm usually one to mind my own business, but I heard that"
    ],
    accuse: [
        "having sex",
        "dabbing",
        "daydreaming",
        "being a little bitch",
        "lying to a person of authority",
        "faking their death",
        "being gay and doing crimes",
        "transing their gender",
        "kidnapping someone's beloved pet",
        "eating literal garbage",
        "unhinging their jaw like a snake",
        "sneaking suspiciously into a building here in town",
        "coercing people into giving them their teeth",
        "getting their teeth stolen",
        "planning to commit treason",
        "getting absolutely wasted",
        "making a deal with the fae",
        "tilting at windmills",
        "catfishing the constable with pictures of the queen",
        "catfishing the mayor with pictures of the queen",
        "catfishing the queen with pictures of snakes",
        "eating a big pile of spaghetti and not sharing any of it",
        "threatening to kill somebody",
        "killing somebody",
        "hiding a body",
        "pickpocketing their best friend",
        "kissing the homies goodnight",
        "t-posing for dominance",
        "being a fucking narc",
        "being awful to the police",
        "pulling a dragon's tail",
        "vandalizing the local tavern",
        "getting involved with an illicit underground unicorn fight club",
        "playing Yu-Gi-Oh",
        "undermining the government at every turn",
        "falling on their ass",
        "eating shit and falling off their horse",
        "riding topless",
        "stealing from the church"
    ]
};

// NPC Builder, Rumors
const characters = {
    players: [
        "Karlaen Sin'del",
        "Lord Swift Fingers",
        "Delawyn Liamour",
        "Ursa Oak",
        "Elias Athear",
        "Agon Caradin of Canton", 
        "Jaxx Malendarr",
        "Alwin Malendarr",
        "Verdic Bin Corsica il-Pachero os-Farwhen",
        "Baratraxar Hopsworth Greynettle",
        "Isla Marillon Shallowcove",
        "Cerradus",
        "Tallian Gratz",
        "Waylund",
        "Kilgor",
        "Leisa Vadi",
        "Tacitus Jules Hooker",
        "Sigmund Bjorvika",
        "Relldar Delandrielle",
        "Elen",
        "Remi Dubois",
        "Grylis Sharptongue",
        "Azalea Briarwood",
        "Knox",
        "Norain Wulf",
        "Wren",
        "Arl",
        "Ankh Nym'dul",
        "Brandan Von Naegling",
        "Calus Varin",
        "Alyssandra Lamoran",
        "Myrtle Muckandmire",
        "Gregnobulous Frogmagourke",
        "Rina Duskwalker",
        "Crittamon Luckstryder",
        "Whisper",
        "Artharias",
        "Theran Slate",
        "Brigid",
        "Cayn",
        "Ekyo",
        "Meeps Swag McMuffin",
        "Clay",
        "Fenrisse Starling",
        "Balthazar",
        "Koth Stalgrim",
        "Hilde",
        "Zumlar Mystralith",
        "Cotter Cornwall",
        "Gizzet Moonbright (Giz'Ora)",
        "Yinren Valgon",
        "Alistair Caliban",
        "Willow",
        "Grimstone",
        "Pappa Varnak",
        "Caleb Urtgard",
        "Zav",
        "Minyo Hasselblöd",
        "Mallazyr 'Dexter' Teken'Tlar",
        "Munta Theynore",
        "Esther Melea Artemis Glade",
        "Esperanza Ta Zata",
        "Riddle",
        "Lorik Ovgar",
        "Thordric Magestone",
        "Hedrin Longfellow",
        "Taliesin Finch",
        "Seraphina Mehri",
        "Sueb Dew",
        "Maurmagil",
        "Ezra",
        "Nakoa",
        "Eitri Hawthorne of the Storm's Mistress",
        "Lucius Grell",
        "Mayax",
        "Matias Elson",
        "Ven",
        "Trisrora",
        "Hart",
        "Catanya",
        "Xanthion Stonebreaker",
        "Saige",
        "Vendal Sihde",
        "Chessaul Nymval",
        "Lady Indy L'Rhine",
        "Vitae Silias",
        "Ajax Ardak",
        "Wenek",
        "Magnus Stillmyst",
        "Mathers",
        "Marlonious Finch",
        "Owen Anderson",
        "Aishin Stormcloud",
        "Alansar Trignot",
        "Victus Krane",
        "Tass",
        "Opulus",
        "Grom",
        "Geillia Mabrik",
        "Amuck Ambrosius",
        "Traveler"
    ],
    faceRoles: [
        "Lord Proctor Behran",
        "Farmer Grey",
        "Octavious",
        "Dennis",
        "Zephyr Zax",
        "Druidkeeper Hesperides Crimsonvine",
        "Dr. Emmet Calhoun",
        "Dr. Arianaya Bell-Dreveaux",
        "Euclid, the Bawdy Bard",
        "Ser Amaris",
        "Fable",
        "Xavier Denerethion",
        "Baron Dworrin Stonethrust",
        "Ali from Owlstone Keep",
        "Paradiddle the Odditites Merchant",
        "Nalfor Morehammer",
        "Norrin Radd",
        "Duke Geralt Marielle",
        "Lord Auranos Ashbridge",
        "Getorix Wahl",
        "Oleg Hammersong",
        "Roark Galt",
        "Johann Becket",
        "Bellator Zhao",
        "Mythria Diamantis",
        "Count Amedeo",
        "Master Trapmaker Dom Sourfang",
        "Joff Godley"
    ],
    fakeFirst:["Billy","Bobby","Mary","Barry","Steven","Marlon","Rachel","Shelby","Eliza","Elizabeth","Joseph","Andy","Arietta","Morgan","Taylor","Tristan","Kai","Anabelle","Duke","Esteban","Antonio","Anthony","Tony","Jackie","John","Mike","Michael","Chev","Mandy","Sully","Joel","Roger","Peter","Connor","Brian","Brendan","Emmy","Isaac","Melissa","Jaime","Jesse","Dakota","Jackson","Sawyer","Xavier","Ester","Tien","Logan","James","Mason","Jason","Calvin","Caleb","Ada","Clay","Gerard","Amy","Lydia","Eugenia","Rose","Jade","Jane","Roxy","Dave","David","Alexis","Jake","Dirk","Sarah","Raleigh","Nikolai","Laila","Emerald","Marcus","Marc","Mark","Caroline","Katie","Kaitlin","Bridget","Haley","Jack","Lauren","Reya","Letitia","Axle","Alex","Rae","Fae","Danny","Dani","Hugo","Juan","Johnny","Paul","Dominic","Mia","Michelle","Dwayne","Chris","Antigone","Maria","Mehak","Vishali","Iris","Shane","Sam","Jimmy","Isabella","Wendy","Thomas","Dan","Daniel","Elias","Cris","Norbert"],
    fakeLast: ["Venitzo","Nightlocke","Shelley","Brando","Grey","Stevenson","Andrews","McGrath","Wheeler","Taylor","Brodey","Lee","Han","Collins","LeBeau","Blackwood","Jackson","Stratman","Smith","Filli","Miller","Merlino","Fox","Waldron","Rogers","Adams","de la Cruz","Santiago","Lessio","Belen","Rodriguez","Connors","Parker","Barnes","Price","Sawyer","Wolfe","Mayer","Howlett","Freyason","Foster","Reynolds","Thorne","Owens","Doe","Morse","Paura","Walters","Ivanofski","St. Claire","Shaughnessy","Carson","Fianna","Delarose","Darwin","Red","Green","Perez","Runner","Walker","Toretto","DiArcangelo","Desantos","Tavares","Diamond","Wu","Demehri","Cahill","Brown","Fenton","Rienton"]
};

// Rumors
const monsters = [
    "Boguns",
    "Gnolls",
    "Banshees",
    "Undead",
    "Elementals",
    "Nutkin"
];

// Adventure Generator
const verbs = {    
    present: [
        "kill",
        "bribe",
        "explore",
        "summon",
        "transport",
        "steal",
        "hunt",
        "torture",
        "gather",
        "curse",
        "enchant",
        "disable",
        "create",
        "attack",
        "write",
        "assassinate",
        "kidnap",
        "sabotage",
        "dishonor",
        "marry",
        "travel",
        "sneak",
        "unleash",
        "escort",
        "dig",
        "protect",
        "blackmail",
        "rob",
        "nap",
        "disfigure",
        "forage",
        "impersonate",
        "hide",
        "destroy",
        "search for",
        "seek",
        "flee",
        "trick",
        "manipulate",
        "rest",
        "blockade",
        "discover",
        "invade",
        "embarrass",
        "look for",
        "camp",
        "recruit",
        "terrorize",
        "invest in",
        "invest suspiciously heavily in",
        "dupe",
        "abuse",
        "tax",
        "spread",
        "make",
        "organize",
        "request",
        "challenge",
        "cause",
        "raise",
        "sail",
        "raze",
        "build",
        "look for",
        "glean",
        "paint",
        "excavate",
        "impede",
        "perform",
        "keep",
        "control",
        "capture",
        "sacrifice",
        "reconnaissance for",
        "prey",
        "cheat",
        "shirk",
        "stir",
        "incite",
        "deflect",
        "quest for",
        "invoke",
        "propagate",
        "sell",
        "wage war on",
        "build up",
        "hinder",
        "secure",
        "deny",
        "resurrect",
        "picket",
        "drown",
        "vandalize",
        "claim",
        "take",
        "stifle",
        "over-run",
        "starve",
        "defile",
        "cull",
        "establish",
        "proselytize",
        "pass",
        "slow",
        "disguise",
        "restore",
        "get",
        "murder",
        "declare war on",
        "daydream about",
        "lie to",
        "fake",
        "eat",
        "coerce",
        "catfish",
        "get involved with",
        "play with",
        "become",
        "betray",
        "bind",
        "break",
        "bring back",
        "bring",
        "burn",
        "catch",
        "change",
        "clear",
        "conquer",
        "convert",
        "cure",
        "defeat",
        "delay",
        "earn",
        "eliminate",
        "end",
        "enslave",
        "erase",
        "escape",
        "expand",
        "expose",
        "extinguish",
        "fight against",
        "find",
        "form",
        "found",
        "free",
        "heal",
        "hold",
        "implode",
        "join",
        "locate",
        "make fun of",
        "make substantial profits on",
        "negotiate",
        "open",
        "overthrow",
        "plan for",
        "prove",
        "reset",
        "return",
        "revive",
        "save",
        "shame",
        "slaughter",
        "start",
        "stick it to",
        "turn back",
        "undo",
        "unite",
        "worship",
        "ally themselves with",
        "awaken",
        "pay",
        "appease",
        "avert",
        "topple",
        "fulfill",
        "acquire",
        "banish",
        "sow",
        "gain",
        "complete",
        "shake",
        "show the inferiority of",
        "crash",
        "corner the market in",
        "renegotiate",
        "bring low"
    ],
    gerund: [
        "killing",
        "bribing",
        "exploring",
        "summoning",
        "transporting",
        "stealing",
        "hunting",
        "torturing",
        "gathering",
        "cursing",
        "enchanting",
        "disabling",
        "creating",
        "attacking",
        "writing",
        "assassinating",
        "kidnapping",
        "sabotaging",
        "dishonoring",
        "marrying",
        "traveling",
        "sneaking",
        "unleashing",
        "escorting",
        "digging",
        "protecting",
        "blackmailing",
        "robbing",
        "napping",
        "disfiguring",
        "foraging",
        "impersonating",
        "hiding",
        "destroying",
        "searching for",
        "seeking",
        "fleeing",
        "tricking",
        "manipulating",
        "resting",
        "blockading",
        "discovering",
        "invading",
        "embarrassing",
        "looking",
        "camping",
        "recruiting",
        "terrorizing",
        "investing in",
        "investing suspiciously heavily in",
        "duping",
        "abusing",
        "taxing",
        "spreading",
        "making",
        "organizing",
        "requesting",
        "challenging",
        "causing",
        "raising",
        "sailing",
        "razing",
        "building",
        "looking for",
        "gleaning",
        "painting",
        "excavating",
        "impeding",
        "performing",
        "keeping",
        "controlling",
        "capturing",
        "sacrificing",
        "reconnaissancing for",
        "preying",
        "cheating",
        "shirking",
        "stirring",
        "inciting",
        "deflecting",
        "questing for",
        "searching for",
        "invoking",
        "propagating",
        "selling",
        "waging war on",
        "building up",
        "hindering",
        "securing",
        "denying",
        "resurrecting",
        "picketing",
        "drowning",
        "vandalizing",
        "claiming",
        "taking",
        "stifling",
        "over-running",
        "starving",
        "defiling",
        "culling",
        "establishing",
        "proselytizing",
        "passing",
        "slowing",
        "disguising",
        "restoring",
        "getting",
        "murdering",
        "declaring war on",
        "daydreaming about",
        "lying to",
        "faking",
        "eating",
        "coercing",
        "catfishing",
        "getting involved with",
        "playing with",
        "becoming",
        "betraying",
        "binding",
        "breaking",
        "bringing back",
        "bringing",
        "burning",
        "catching",
        "changing",
        "clearing",
        "conquering",
        "converting",
        "curing",
        "defeating",
        "delaying",
        "earning",
        "eliminating",
        "ending",
        "enslaving",
        "erasing",
        "escaping",
        "expanding",
        "exposing",
        "extinguishing",
        "fighting against",
        "finding",
        "forming",
        "founding",
        "freeing",
        "healing",
        "holding",
        "imploding",
        "joining",
        "locating",
        "making fun of",
        "making substantial profits on",
        "negotiating",
        "opening",
        "overthrowing",
        "planning for",
        "proving",
        "reseting",
        "returning",
        "reviving",
        "saving",
        "shaming",
        "slaughtering",
        "starting",
        "sticking it to",
        "turning back",
        "undoing",
        "uniting",
        "worshipping",
        "allying themselves with",
        "awakening",
        "paying",
        "appeasing",
        "averting",
        "toppling",
        "fulfilling",
        "acquiring",
        "banishing",
        "sowing",
        "gaining",
        "completing",
        "shaking",
        "showing the inferiority of",
        "crashing",
        "cornering the market in",
        "renegotiating",
        "bringing low"
    ],
    contPres: [
        "try to", //verb goal noun
        "attempt to",
        "pretend to",
        "plan to",
        "intend to",
        "want to",
        "need to",
        "threaten to"
    ],
    contGer: [
        "trying to", //verb goal noun
        "attempting to",
        "pretending to",
        "planning to",
        "threatening to"
    ],
    continuousOther: [
        "finally"
    ]
}

// Fetch Quest, Rumors, Adventure Generator
const nouns = [
    // Ace-10 of spades from MHoF
    "a sword",
    "a shield",
    "a bottle of alcohol",
    "a knife",
    "a dog",
    // "a fight",
    "a really cool cloak",
    "information",
    "financial compensation",
    "a really big knife",
    "a potion",

    // from the Meme Machine
    "a really tiny knife",
    "a jar",
    "a steamy adult romance novel",
    "a cursed magical item",
    "a small horse",
    "a spyglass",
    "a pair of scissors",
    "a magic item",

    // Adventure Generator
    "new members",
    "travelers",
    "officials",
    "power",
    "followers of another group",
    "the seas",
    "enourmous amount of gold",
    "the king",
    "diseased blankets",
    "a plague's progression",
    "public speeches",
    "peasants",
    "a divine audience",
    "people to a duel",
    "chaos",
    "the dead",
    "away",
    "their lost honor",
    "a city",
    "a fortress",
    "another group",
    "approval",
    "the chosen one",
    "the law",
    "murder",
    "alliances",
    "information",
    "arcane murals",
    "an ancient song",
    "a fleet of warships",
    "sensitive divinations",
    "a low profile",
    "a settlement",
    "the militia",
    "citizens",
    "unstable individuals",
    "themselves",
    "a weak spot",
    "a cure",
    "children",
    "the elderly",
    "the aristocracy",
    "clerics",
    "mages",
    "duty",
    "interest",
    "rebellion",
    "violence",
    "blame",
    "a magical formula",
    "an Archwizard's legendary lost spellbook",
    "privileges",
    "a new ethic",
    "a plague",
    "false hope",
    "a new powerful magic book",
    "rumors",
    "a trade war",
    "a trade monopoly",
    "trade",
    "prices",
    "resources",
    "long-extinct creatures",
    "honest shopkeepers",
    "kittens",
    "creature hybrids",
    "a building site",
    "a rival's masterwork",
    "younger citizens",
    "responsibility",
    "the blame",
    "opposition",
    "the masses",
    "shrines",
    "the herd",
    "an illegal gambling ring",
    "a little bitch",
    "a person of authority",
    "someone's death",
    "someone's beloved pet",
    "literal garbage",
    "a building here in town",
    "stolen teeth",
    "a deal with the fae",
    "the constable",
    "the mayor",
    "snakes",
    "a big pile of spaghetti",
    "somebody",
    "a body",
    "someone's best friend",
    "the homies",
    "the local tavern",
    "an illicit underground unicorn fight club",
    "the government",
    "the church",
    "control",
    "martyrs",
    "the rich",
    "their country for personal gain",
    "a demon",
    "the walls separating reality",
    "a lost loved one",
    "peace",
    "a haven",
    "everything",
    "the notice of a god",
    "history",
    "their names",
    "a nation",
    "a legacy",
    "a new divinity",
    "a powerful magic item",
    "their insanity",
    "a cleric",
    "an army",
    "a wedding",
    "a divinity",
    "a rival",
    "a village",
    "magic",
    "a villain's weakness",
    "who they really are",
    "fame and prestige",
    "their rival",
    "a local noble",
    "a rivalry",
    "a war",
    "their targets",
    "their past",
    "punishment",
    "their domains",
    "the court",
    "a race",
    "against a rival",
    "rest",
    "the real answers",
    "a cult",
    "a new society",
    "a new community",
    "the princess",
    "their people",
    "revenge",
    "a great wound upon the land",
    "a great wound upon the people",
    "their treasure",
    "a coup",
    "a vampire",
    "their goddess",
    "colony of humanoids",
    "a king",
    "a tome of unspeakable truths",
    "a truce",
    "an agreement with the archenemy",
    "a magical gate",
    "a portal to another dimension",
    "the empress",
    "the next season",
    "their bravery",
    "followers",
    "time",
    "the ancients",
    "a forgotten god",
    "a knight",
    "a group of people",
    "a civil war",
    "a new world order",
    "'the man'",
    "a monster",
    "reality",
    "the lands",
    "unspeakable evil",
    "a forgotten divinity",
    "a vampire lord",
    "thousands of ghosts",
    "a werewolf lair",
    "their debts",
    "a demoness",
    "unnatural disaster",
    "disaster",
    "the kingdom",
    "respect",
    "a prophecy",
    "a prophecy's fulfillment",
    "destiny",
    "their children",
    "hostages",
    "the Serpent God",
    "their reputation",
    "a riot",
    "disorder",
    "treachery",
    "leverage",
    "a menagerie of creatures",
    "their collections",
    "doomsday",
    "their successors",
    "their rival's disgrace",
    "their place in history",
    "the economy",
    "the market",
    "an agreement",
    "the animals",
    "the mighty",
    "the prophecy",
    
    //means 
    "fake identities",
    "an old rusty chain",
    "a dragon's support",
    "magical man-catchers",
    "a family heirloom weapon",
    "threats and intimidation",
    "misdirection",
    "pure wits",
    "a diadem of control",
    "a powerful magic wand",
    "forged documents",
    "flows of gold",
    "a plague of locusts",
    "the iron hand of the tyrant",
    "extortion",
    "deception",
    "a strange music box",
    "extreme discretion",
    "an enchanted quill",
    "a key",
    "forbidden tomes",
    "powerful friends",
    "information from a contact person",
    "deep pockets",
    "their dormant magical talent",
    "an ancient holy symbol",
    "secret documents",
    "a recently found artifact",
    "the power vested in them by law",
    "an army of undead",
    "the skull of a long dead necromancer",
    "a god's blessing",
    "a laissez-faire attitude",
    "a cursed weapon",
    "the king's orders in hand",
    "a magical army",
    "the power of prayer",
    "a slayer",
    "divine blessings",
    "a band of mercenaries",
    "a con artists glib",
    "the heart of a tree of life",
    "the support of the church",
    "a very intricate and detailed masterplan",
    "a thousand tortured souls",
    "an astrolabe",
    "the bones of an ancient mage",
    "the support of a mob",
    "the help of bribed bureaucrats",
    "blackmail",
    "a god's finger",
    "an insatiable hunger",
    "false promises",
    "blatant lies",
    "the blood of the innocent",
    "contracts for the gullible",
    "the might of the kingdom's military",
    "the support of the noble court",
    "a dragon's hoard",
    "bribed officials",
    "a stolen artifact",
    "an ancient arrowhead",
    "frenzied devotion",
    "a merfolk bridal veil",
    "a game that is also a test",
    "mass hypnosis",
    "iron will and determination",
    "divine regalia",
    "the hopes of the whole village",
    "a cursed armor",
    "the queen's blessing",
    "little resources left",
    "embalmed corpses",
    "a soulstone",
    "an elf's life essence",
    "an army",
    "a dragon",
    "public officials and decrees",
    "a civil war",
    "sabotage",
    "espionage",
    "drugs",
    "a puppet organization",
    "bribery",
    "alcohol",
    "slaves",
    "contracts",
    "demonic help",
    "the local authority",
    "the local crime underground",
    "market manipulations",
    "cloning",
    "the power of the Ooze",
    "any means necessary",
    "lurid colors",
    "deceptive documents"
];

// Adventure Generator
// where fragments go to die after I tear them apart like confetti
const fragments = {
    goal: [
        // adventure seed generator
        "assume control",
        "become immortal",
        "become king",
        "become martyrs",
        "become rich",
        "betray their country for personal gain",
        "bind a demon",
        "break the walls separating reality",
        "bring a lost loved one back to life",
        "bring domination to their race",
        "bring peace",
        "build a haven",
        "burn everything",
        "catch the notice of a god",
        "change history",
        "clear their names",
        "conquer a nation",
        "convert others to their way of thinking",
        "create a legacy",
        "create a new divinity",
        "create a powerful magic item",
        "cure their insanity",
        "defeat a cleric",
        "defeat an army",
        "delay a wedding",
        "destroy",
        "destroy a divinity",
        "destroy a rival",
        "destroy a village",
        "destroy magic",
        "die",
        "discover a villain's weakness",
        "discover who they really are",
        "earn fame and prestige",
        "eliminate their rival",
        "embarrass a local noble",
        "end a rivalry",
        "end a war",
        "enslave their targets",
        "erase their past",
        "escape punishment",
        "expand their domains",
        "expose the court",
        "extinguish a race",
        "fight against a rival",
        "finally rest",
        "find the real answers",
        "form a cult",
        "form a new society",
        "found a new community",
        "free the princess",
        "free their people",
        "get revenge",
        "heal a great wound upon the land/people",
        "hide",
        "hide their treasure",
        "hold a coup",
        "hunt a vampire",
        "implode the court",
        "join the court",
        "keep their godess happy",
        "kill a colony of humanoids",
        "kill a king",
        "locate a tome of unspeakable truths",
        "make fun of",
        "make substantial profits",
        "negotiate a truce",
        "negotiate an agreement with the arch enemy",
        "open a magical gate",
        "open a portal to another dimension",
        "overthrow the empress",
        "plan for the next season",
        "prove their bravery",
        "recruit followers",
        "reset time",
        "return the ancients",
        "revive a forgotten god",
        "save themselves",
        "shame a knight",
        "slaughter a group of people",
        "start a civil war",
        "start a new world order",
        "start a war",
        "stick it to 'the man'",
        "summon a monster",
        "turn back time",
        "undo reality",
        "unite the lands",
        "unleash unspeakable evil",
        "worship a forgotten divinity",
        "turn people undead",
        "ally themselves with a vampire lord",
        "awake thousands of ghosts",
        "find a werewolf lair",
        "pay their debts",
        "appease a demoness",
        "avert unnatural disaster",
        "avert disaster",
        "topple the kingdom",
        "earn respect",
        "fulfill a prophecy",
        "avert a prophecy's fulfillment",
        "cheat destiny",
        "save their children",
        "free hostages",
        "acquire hostages",
        "invoke the Serpent God",
        "banish a demon",
        "restore their reputation",
        "incite a riot",
        "sow disorder",
        "expose treachery",
        "gain hostages",
        "gain leverage",
        "make a menagerie of creatures",
        "complete their collections",
        "shake the government",
        "avert doomsday",
        "show the inferiority of their successors",
        "cause their rival disgrace",
        "secure their place in history",
        "crash the economy",
        "corner the market",
        "renegotiate an agreement",
        "save the kingdom",
        "save the animals",
        "bring low the mighty",
        "fulfill the prophecy"
    ],
    action: [
        // adventure seed generator
        "declaring war on",
        "recruiting new members",
        "terrorizing travelers",
        "investing suspiciously heavily in",
        "attempting to proselytize",
        "duping officials",
        "trying to pass a bribe",
        "abusing power",
        "attacking followers of another group",
        "exploring the seas",
        "taxing enourmous amount of gold",
        "manipulating the king",
        "spreading diseased blankets",
        "trying to slow a plague's progression",
        "making public speeches",
        "organizing peasants",
        "requesting a divine audience",
        "in disguise",
        "challenging people to a duel",
        "causing chaos",
        "raising the dead",
        "sailing away",
        "attempting to restore their lost honor",
        "razing a city",
        "building a fortress",
        "conspiring with another group",
        "trying to get approval",
        "on official business",
        "looking for the chosen one",
        "abusing the law",
        "being framed for murder",
        "sabotaging alliances",
        "gleaning information",
        "painting arcane murals",
        "excavating an ancient song",
        "building a fleet of warships",
        "impeding travellers",
        "performing sensitive divinations",
        "on a pilgramage",
        "keeping a low profile",
        "building a settlement",
        "controlling the militia",
        "capturing citizens",
        "looking for unstable individuals",
        "sacrificing themselves",
        "reconnaissancing for a weak spot",
        "seeking a cure",
        "preying on children",
        "cheating the elderly",
        "duping the aristocracy",
        "robbing clerics",
        "terrorizing mages",
        "shirking duty",
        "pretending interest",
        "stirring rebellion",
        "inciting violence",
        "deflecting blame",
        "questing for a magical formula",
        "searching for an Archwizard's legendary lost spellbook",
        "invoking privileges",
        "propagating a new ethic",
        "spreading a plague",
        "selling false hope",
        "writing a new powerful magic book",
        "spreading rumors",
        "waging a trade war",
        "building up a trade monopoly",
        "hindering trade",
        "manipulating prices",
        "securing resources",
        "denying resources",
        "resurrecting long extinct creatures",
        "picketing honest shopkeepers",
        "drowning kittens",
        "creating creature hybrids",
        "sabotaging a building site",
        "vandalizes a rival's masterwork",
        "trying to trick younger citizens",
        "claiming responsibility",
        "taking the blame",
        "stifling opposition",
        "over-running resources",
        "starving the masses",
        "defiling shrines",
        "'culling the herd'",
        "planning to estalish an illegal gambling ring",
        "intending to kidnap children from their parents",

        // rumor accuse
        "daydreaming",
        "being a little bitch",
        "lying to a person of authority",
        "faking their death",
        "being gay and doing crimes",
        "transing their gender",
        "kidnapping someone's beloved pet",
        "eating literal garbage",
        "unhinging their jaw like a snake",
        "sneaking suspiciously into a building here in town",
        "coercing people into giving them their teeth",
        "getting their teeth stolen",
        "planning to commit treason",
        "getting absolutely wasted",
        "making a deal with the fae",
        "tilting at windmills",
        "catfishing the constable with pictures of the queen",
        "catfishing the mayor with pictures of the queen",
        "catfishing the queen with pictures of snakes",
        "eating a big pile of spaghetti and not sharing any of it",
        "threatening to kill somebody",
        "killing somebody",
        "hiding a body",
        "pickpocketing their best friend",
        "kissing the homies goodnight",
        "t-posing for dominance",
        "being a fucking narc",
        "being awful to the police",
        "pulling a dragon's tail",
        "vandalizing the local tavern",
        "getting involved with an illicit underground unicorn fight club",
        "playing Yu-Gi-Oh",
        "undermining the government at every turn",
        "falling on their ass",
        "eating shit and falling off their horse",
        "riding topless",
        "stealing from the church"
    ],
    means: [
        // adventure seed generator
        "with fake identities",
        "with an old rusty chain",
        "with a dragon's support",
        "with magical man-catchers",
        "with a family heirloom weapon",
        "with threats and intimidation",
        "with misdirection",
        "by pure wits",
        "with a diadem of control",
        "with a wand of magic missiles",
        "with forged documents",
        "with flows of gold",
        "with a plague of locusts",
        "with the iron hand of the tyrant",
        "by extorting the king",
        "with deception",
        "using a strange music box",
        "with extreme discretion",
        "with an enchanted quill",
        "by deception",
        "with a key",
        "with a rope of braided blood boar hair",
        "with forbidden tomes",
        "with powerful friends",
        "by applying information from a contact person",
        "with deep pockets",
        "by impersonating",
        "by summoning a demon",
        "by applying their dormant magical talent",
        "with an ancient holy symbol",
        "using secrets documents",
        "with a recently found artifact",
        "by the power vested to them by law",
        "with an army of undead",
        "claiming an old testament gives them the right",
        "with the skull of a long dead necromancer",
        "with a god's blessing",
        "with a laissez faire attitude",
        "with a cursed weapon",
        "with the king's orders in hand",
        "with a magical army",
        "using the power of prayer",
        "with a slayer",
        "with divine blessings",
        "with a band of mercenaries",
        "with a con artists glib",
        "with the heart of a tree of life",
        "with the support of the church",
        "applying a very intricate and detailed masterplan",
        "with a thousand tortured souls",
        "with an astrolabe",
        "with the bones of an ancient mage",
        "with the support of a mob",
        "with the help of bribed bureaucrats",
        "with blackmail",
        "with a god's finger",
        "with an insatiable hunger",
        "with false promises",
        "telling blatant lies",
        "by disguising as someone else",
        "by destroying a village",
        "with the blood of the innocent",
        "with contracts for the gullible",
        "with the might of the kingdom's military",
        "with the support of the noble court",
        "with a dragon's hoard",
        "with bribes to officials",
        "with a stolen artifact",
        "with an ancient arrowhead",
        "with frenzied devotion",
        "with a merfolk bridal veil",
        "by a game that is also a test",
        "with mass hypnosis",
        "with iron will and determination",
        "with divine regalia",
        "with the hopes of the whole village",
        "with a cursed armor",
        "with the queen's blessing",
        "with little resources left",
        "with the embalmed corpses of twin babies",
        "with a soulstone",
        "with an elf's life essence",
        "with an army",
        "with a dragon",
        "through public officials and decrees",
        "through a civil war",
        "through sabotage",
        "through espionage",
        "with drugs",
        "by controlling a puppet organization",
        "by bribery",
        "with alcohol",
        "with slaves",
        "by contracts",
        "with demonic help",
        "with the local authority",
        "with the local crime underground",
        "with market manipulations",
        "via cloning",
        "by the power of the Ooze",
        "by any means necessary",
        "with lurid colors",
        "with deceptive documents"
    ],
    secretThirdThing: [
        "on official business",       
        "on a pilgramage",        
        "conspiring with",
        "intents to kidnap children from their parents", //verb
        "being framed for", // this also belongs in a separate thing
        "squatting",
        "in disguise",
    ]
}
// VARIABLES END

// FUNCTIONS START
// random string for all generators
function randomString(arr) {
    const randomIndex = Math.floor(Math.random() * arr.length);
    const item = arr[randomIndex];
    return item;
}

// Plot Test
function plotGen() {
    const type = randomString(plotElem.type);
    const tone = randomString(plotElem.tone);
    const genre = randomString(plotElem.genre);

    document.getElementById("pt-plot").innerHTML = "<p>This plot is going to be <b>" + tone + " " + genre + " " + type + ".</b></p>"
}

// Fetch Quest
const qQuest = [
    "quest 1",
    "quest 2"
];

let questSelect = "";

function questGen() {
    questSelect = randomString(qQuest);

    const qItem = randomString(nouns);
    const qProperty = randomString(property);
    const qGoal = randomString(fragments.goal);
    const qMotive = randomString(quest.motivation);
    const qTwist = randomString(quest.twist);

    switch(questSelect) {
        case "quest 1":
            document.getElementById("qq-quest").innerHTML = "<p>The party is looking for <b>" + qItem + "</b> that <b>" + qProperty + ".</b> They are looking for this <b>" + qMotive + ",</b> but the thing is that <b>" + qTwist + ".</b></p>";
        break;
        case "quest 2":
            document.getElementById("qq-quest").innerHTML = "<p>The party is looking for <b>" + qItem + "</b> that <b>" + qProperty + "</b> in order to <b>" + qGoal + ".</b> They want this <b>" + qMotive + ",</b> but what they haven't realized yet is that <b>" + qTwist + ".</b></p>";
        break;
    }
}

// Adventure Generator
const adventureType = [
    "adventure 1",
    "adventure 2",
    // "adventure 3",
    // "adventure 4"
];

const subjectType = [
    "singular 1",
    "singular 2",
    "plural"
]

const actionType = [ 
    "action 1",
    "action 2",
    "action 3",
    "action 4"
];

const methodType = [
    "method 1",
    "method 2",
    "method 3",
    "method 4"
];

let adventureSelect = "";
let subjectSelect = "";
let actionSelect = "";
let methodSelect = "";

function adventureGen() {
    adventureSelect = randomString(adventureType);
    subjectSelect = randomString(subjectType);
    actionSelect = randomString(actionType);
    methodSelect = randomString(methodType);

    const agChara = randomString(chara.chara);
    const agCharTrait = randomString(chara.trait);
    const agCharNoun = randomString(chara.noun);
    const agAdjective = randomString(chara.adjective);
    const agGroup = randomString(chara.group);
    const agMembers = randomString(chara.members);

    const agGoal = randomString(fragments.goal);
    const agPlace = randomString(quest.place);
    const agMotive = randomString(quest.motivation);
    const agTwist = randomString(quest.twist);

    let agSubject = "";
    let agAction = "";
    let agMethod = "";

    const agActionFrag = randomString(fragments.action);
    const agMethodFrag = randomString(fragments.means);
    const agMethodNoun = randomString(nouns);

    const agNounOne = randomString(nouns);
    const agNounTwo = randomString(nouns);

    const agPresent = randomString(verbs.present)
    const agGerund = randomString(verbs.gerund);
    // const agContPres = randomString(verbs.contPres); //[try] to [verb] [noun]
    const agContGer = randomString(verbs.contGer);

    switch (subjectSelect) {
        case "singular 1":
            agSubject = agChara + "</b> who <b>" + agCharTrait + "</b> is";
        break;
        case "singular 2":
            agSubject = agAdjective + " " + agCharNoun + "</b> is";
        break;
        case "plural":
            agSubject = agAdjective + " " + agGroup + "</b> of <b>" + agMembers + "</b> are";
        break;
    }

    switch (actionSelect) {
        case "action 1": //action fragment
            agAction = "<b>" + agActionFrag;
        break;
        case "action 2": //are [verb]ing [noun]
            agAction = "<b>" + agGerund + " " + agNounOne;
        break;
        case "action 3": //[trying] to [verb] [noun]
            agAction = "<b>" + agContGer + " " + agPresent + " " + agNounOne;
        break;
        case "action 4": //try to [verb] [noun]
            agAction = "trying to <b>" + agPresent + " " + agNounOne;
        break;
        // case "action 5": //[try] to [verb] [noun] //*sigh*, maybe later
        //     agAction = "<b>" + agContPres + " " + agPresent + " " + agNounOne + "</b>";
        // break;
    }

    const agPerson = agSubject + " " + agAction;

    switch (methodSelect) {
        case "method 1":
            agMethod = "<b>" + agMethodFrag;
        break;
        case "method 2":
            agMethod = "</b>using <b>" + agMethodNoun;
        break;
        case "method 3":
            agMethod = "</b>with the help of <b>" + agMethodNoun;
        break;
        case "method 4": //[action] by [gerund] [noun]
            agMethod = "</b>by <b>" + agGerund + " " + agNounTwo;
        break;
    }

    switch (adventureSelect) {
        // multiple lines
        case "adventure 1":
            document.getElementById("ag-adventure").innerHTML = "<p>In this story, <b>" + agPerson + " " + agPlace  + ".</b></p>" + 
            "<p>Their goal is to <b>" + agGoal + " " + agMethod + " " + agMotive + ",</b> but <b>" + agTwist + ".</b></p>";
        break;
        case "adventure 2":
            document.getElementById("ag-adventure").innerHTML = "<p>This story takes place <b>" + agPlace +",</b> where <b>" + agPerson + ".</b> Their goal is to <b>" + agGoal + " " + agMethod + ".</b></p>" + 
            "<p>They are doing this <b>" + agMotive + ",</b> but <b>" + agTwist + ".</b></p>";
        break;
        case "adventure 3": // This one's just for workshopping stuff
            document.getElementById("ag-adventure").innerHTML = "<p>This story takes place <b>" + agPlace +",</b> where <b>" + agPerson + " " + agMethod + ".</b></p>";
        break;
    }
}

// NPC Builder
const npcParty = [
    "party 1",
    "party 2",
    "party 3",
    "party 4",
    "party 5",
    "party 6",
    "party 7"
];

let partySelect = "";

function npcGen() {
    partySelect = randomString(npcParty);

    const charaOne = randomString(chara.chara);
    const traitOne = randomString(chara.trait);

    const charaTwo = randomString(chara.chara);
    const traitTwo = randomString(chara.trait);
    
    const charaThree = randomString(chara.chara);
    const traitThree = randomString(chara.trait);

    const fakeFirst = randomString(characters.fakeFirst);
    const fakeLast = randomString(characters.fakeLast);
    const fakeRole = fakeFirst + " " + fakeLast;

    const adjectiveOne = randomString(chara.adjective);
    const nounOne = randomString(chara.noun);
    const charaConcatOne = adjectiveOne + " " + nounOne;

    const adjectiveTwo = randomString(chara.adjective);
    const nounTwo = randomString(chara.noun);
    const charaConcatTwo = adjectiveTwo + " " + nounTwo;

    const adjectiveThree = randomString(chara.adjective);
    const nounThree = randomString(chara.noun);
    const charaConcatThree = adjectiveThree + " " + nounThree;

    switch(partySelect) {
        case "party 1":
            document.getElementById("npc-party").innerHTML = "<p>Our party includes <b>" + charaOne + "</b> who <b>" + traitOne + ".</b></p>";
        break;
        case "party 2":
            document.getElementById("npc-party").innerHTML = "<p>Our party includes <b>" + charaOne + "</b> who <b>" + traitOne + ",</b> and <b>" + charaTwo + "</b> who <b>" + traitTwo + ".</b></p>";
        break;
        case "party 3":
            document.getElementById("npc-party").innerHTML = "<p>Our party includes <b>" + charaOne + "</b> who <b>" + traitOne + ", " + charaTwo + "</b> who <b>" + traitTwo + ",</b> and <b>" + charaThree + "</b> who <b>" + traitThree + ".</b></p>";
        break;
        case "party 4":
            document.getElementById("npc-party").innerHTML = "<p>Our party includes <b>" + charaOne + "</b> named <b>" + fakeRole + "</b> who <b>" + traitOne + ".</b></p>";
        break;
        case "party 5":
            document.getElementById("npc-party").innerHTML = "<p>Our party includes <b>" + charaConcatOne + "</b> who <b>" + traitOne + ".</b></p>";
        break;
        case "party 6":
            document.getElementById("npc-party").innerHTML = "<p>Our party includes <b>" + charaConcatOne + "</b> who <b>" + traitOne + ",</b> and <b>" + charaConcatTwo + "</b> who <b>" + traitTwo + ".</b></p>";
        break;
        case "party 7":
            document.getElementById("npc-party").innerHTML = "<p>Our party includes <b>" + charaConcatOne + ", " + charaConcatTwo + ",</b> and <b>" + charaConcatThree + ".</b></p>";
        break;
    }
}

// Rumors
const rRumors = [
    "rumor 1",
    "rumor 2",
    "rumor 3",
    "rumor 4",
    "rumor 5",
    "rumor 6",
    "rumor 7",
    "rumor 8",
    "rumor 9",
    "rumor 10",
    "rumor 11",
    "rumor 12"
];

const personOne = [
    "player character",
    "face role",
    "fake role 1",
    "fake role 2"
];

const personTwo = [
    "player character",
    "face role",
    "fake role"
];

let rumorSelect = "";
let personSelect = "";
let personSelectAlt = "";

function rumorGen() {
    rumorSelect = randomString(rRumors);
    personSelect = randomString(personOne);
    personSelectAlt = randomString(personTwo);

    const rumor_character = randomString(characters.players);
    const rumor_face_role = randomString(characters.faceRoles);
    const rumor_fake_first = randomString(characters.fakeFirst);
    const rumor_fake_last = randomString(characters.fakeLast);

    const rumor_character_alt = randomString(characters.players);
    const rumor_face_role_alt = randomString(characters.faceRoles);
    const rumor_fake_first_alt = randomString(characters.fakeFirst);
    const rumor_fake_last_alt = randomString(characters.fakeLast);

    let rumor_person = "";
    let rumor_person_alt = "";
    
    const rumor_source = randomString(rumors.source);
    const rumor_item = randomString(nouns);
    const rumor_property = randomString(property);
    const rumor_monsters = randomString(monsters);
    const rumor_trait = randomString(chara.trait);
    const rumor_accuse = randomString(rumors.accuse);

    const rumor_chara = randomString(chara.chara);
    const rumor_chara_alt = randomString(chara.chara);

    switch (personSelect) {
        case "player character":
            rumor_person = "<b>" + rumor_character + "</b>";
        break;
        case "face role":
            rumor_person = "<b>" + rumor_face_role + "</b>";
        break;
        case "fake role 1":
            rumor_person = "someone named <b>" + rumor_fake_first + " " + rumor_fake_last + "</b>";
        break;
        case "fake role 2":
            rumor_person = "<b>" + rumor_chara + "</b> named <b>" + rumor_fake_first + " " + rumor_fake_last + "</b>";
        break;
    }

    switch (personSelectAlt) {
        case "player character":
            rumor_person_alt = "<b>" + rumor_character_alt + "</b>";
        break;
        case "face role":
            rumor_person_alt = "<b>" + rumor_face_role_alt + "</b>";
        break;
        case "fake role":
            rumor_person_alt = "someone named <b>" + rumor_fake_first_alt + " " + rumor_fake_last_alt + "</b>";
        break;
    }

    switch (rumorSelect) {
        case "rumor 1":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " + rumor_person + " has <b>" + rumor_item + "</b> that <b>" + rumor_property + ".</b></p>";
        break;
        case "rumor 2":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " +  rumor_person + " was seen <b>" + rumor_accuse + ".</b></p>";
        break;
        case "rumor 3":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " + rumor_person + " is looking for some help with something.</p>";
        break;
        case "rumor 4":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " + rumor_person + " is looking for <b>" + rumor_item + ".</b></p>";
        break;
        case "rumor 5":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " + rumor_person + " is looking for <b>" + rumor_item + "</b> that <b>" + rumor_property + ".</b></p>";
        break;
        case "rumor 6":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " they may be upping woodland patrols due to a rise in the number of <b>" + rumor_monsters + ".</b></p>";
        break;
        case "rumor 7":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " + rumor_person + " was asking around for <b>" + rumor_chara_alt + ".</b></p>";
        break;
        case "rumor 8":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " + rumor_person + " was asking around for someone who <b>" + rumor_trait + ".</b></p>";
        break;
        case "rumor 9":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " +  rumor_person + " <b>" + rumor_trait + ".</b></p>";
        break;
        case "rumor 10":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " +  rumor_person_alt + " is <b>" + rumor_chara + ".</b></p>";
        break;
        case "rumor 11":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " +  rumor_person_alt + " was asking around for <b>" + rumor_person + ".</b></p>";
        break;
        case "rumor 12":
            document.getElementById("rm-rumor").innerHTML = "<p>" + rumor_source + " " +  rumor_person + " was seen <b>" + rumor_accuse + "</b> with <b>" + rumor_person_alt + ".</b></p>";
        break;
    }
}