const npcElements = {
    charType: [
        "a peasant girl",
        "a warrior",
        "a mage",
        "a lad",
        "a fruit-seller",
        "a sellsword",
        "a nomad",
        "a lord",
        "a knight",
        "an assassin",
        "a gentleman thief",
        "a soldier",
        "an empress",
        "a monk",
        "a ranger",
        "a rogue",
        "a ruffian",
        "a sorceror",
        "a witch",
        "an outlaw",
        "a woodsman",
        "a warlord",
        "a noblewoman",
        "a monsterologist",
        "a gentlewoman thief",
        "a druid",
        "a bard",
        "a young boy",
        "a swordmaster",
        "an apprentice",
        "an assassin-in-training",
        "a page",
        "a troubadour",
        "an enchantress-in-training",
        "an ogre",
        "a summoner-in-training",
        "a brigand",
        "a sorceror",
        "a dragon",
        "an elven prince",
        "a witch-in-training",
        "a centaur",
        "a charlatan",
        "a necromancer-in-training",
        "an enchanter",
        "a goblin",
        "a vampire",
        "a genie",
        "a shaman",
        "a prophet-in-training",
        "a sorceror-in-training",
        "a troll",
        "a pickpocket",

        "an eccentric candyman",
        "a coalescer",
        "an excavator",
        "a harvester",
        "a logger",
        "a skinner",
        "a farmer",
        "a hunter",
        "a lumberjack",
        "a miner",
        "a panner",
        "a butcher",
        "a carpenter",
        "a gemcutter",
        "a glassmaker",
        "a papermaker",
        "a smelter",
        "a tanner",
        "a weaver",
        "an architect",
        "a blacksmith",
        "a brewer",
        "a chef",
        "a glassblower",
        "a lapidary",
        "a leatherworker",
        "a tailor",
        "a trapmaker",
        "a woodworker",
        "an appraiser",
        "a laborer",
        "a mender",

        "a retail employee",
        "a werewolf",
        "a feral child",
        "a snake-oil salesman",
        "an influencer",
        "a cowboy",
        "a pirate",
        "a rat",
        "a child psychologist",
        "a ghost-hunter",
        "an archivist",
        "a creature",
        "a demolitions expert",
        "a goose",
        "a duelist",
        "a dog",
        "a construct",
        "a landlord",
        "a celebrity chef",
        "the village idiot",
        "some old guy",
        "a tax-evader",
        "a draft dodger",
        "your mom",
        "a pyrotechnician",
        "an arsonist",
        "a professional arsonist",
        "retired assassin",
        "a hedgehog turtle hybrid",
        "a goth",
        "a clown",
        "an entire circus of clowns",
        "three possums in a trench coat",
        "a doctor"
    ],
    trait: [
        "can be restless",
        "can be ambitious",
        "is kind",
        "used to be idealistic",
        "is past prime",
        "can be brusque",
        "is stubborn to a fault",
        "has not laughed in a long time",
        "lies more often than not",
        "is surprisingly gentle",
        "once was hopeful",
        "can be independently-minded",
        "can be selfish",
        "can be sharp",
        "can be over-critical",
        "tends to be reckless",
        "is abrasive",
        "has become aimless",
        "has a lot of defense mechanisms",
        "can be cold",
        "has a tendency to be cowardly",
        "is destructive",
        "can be detached",
        "can be judgemental",
        "has a sense of humor",
        "has a reputation for being melodramatic",
        "has burnt every bridge",
        "can be vain",
        "has become withdrawn",
        "is taciturn",
        "can be stoic",
        "is suave",
        "is quick-witted",
        "no longer has any loyalties",
        "has a strong moral compass",
        "has 99 problems, and a sidekick is one of them",
        "is a crank",
        "has a reputation for being eccentric",
        "is misunderstood",
        "is a worrywart",
        "is innocent",
        "is rather unpredictable",
        "is unexpectedly charismatic",
        "has a poker face",
        "is soft-hearted",
        "can be independently-minded",
        "used to be selfish",
        "has many controversial opinions",
        "is deadpan",
        "can be pretentious",
        "is prim",
        "is puritanical",
        "can be tactless",
        "tends to attract trouble",
        "is blind",
        "thrives on drama",
        "can be forgetful",
        "is a drifter",
        "is a chatterbox",
        "is spineless",
        "is rather incompetent",
        "is bright",
        "is sensible to a fault",
        "is a forgiving soul",
        "is braver than most",
        "has no moral code",
        "has run away",
        "is affable",
        "is taciturn",
        "is overly polite",
        "can be naïve",
        "can be overly pompous",
        "is overly adventurous",
        "is a lover of books",
        
        "was found by the side of the road",
        "has the attention span of a goldfish",
        "is a conspiracy theorist",
        "loves their wife",
        "doesn't speak the language",
        "thinks they're hot shit",
        "only has one outfit",
        "has not bathed in three weeks",
        "has not been around civilaztion in... some time",
        "is a creature",
        "is really up their own ass about poetry",
        "is terrified of ducks",
        "thinks they're a goose",
        "knows they're a goose",
        "solves all of their problems with card games",
        "has human eyes",
        "eats magic items",
        "is Italian",
        "talks like an anime character",
        "hates children",
        "is divorced",
        "considers themself to be morally grey but has committed several murders",
        "fucks",
        "is blue for no reason",
        "has a tiny creature for a sidekick",
        "likes to break the fourth wall",
        "is a time traveler",
        "is a shitty time traveler",
        "is a shitty wizard",
        "is plagued by visions",
        "has a fat ass",
        "is haunted",
        "really likes dragons",
        "has no idea whats going on",
        "has a child nemesis",
        "smokes way too much weed",
        "has three weed-smoking girlfriends",
        "lies a lot through the newspaper",
        "regularly commits tax fraud",
        "naps in weird places",
        "is an arsonist",
        "doesn't talk to their parents",
        "is bisexual",
        "is a twitch streamer",
        "doesn't believe in hell",
        "is from hell",
        "eats glue",
        "vapes",
        "smokes weed a regular amount",
        "has interesting feelings about spiders",
        "is unreasonably horny",
        "is reasonably horny",
        "doesn't think the sun exists",
        "is a flat earther",
        "believes the earth to be shaped like a donut (for comedy purposes)",
        "believes the earth to be shaped like a donut (because they're kinda hungry right now idk)",
        "is a flat earther to be a dick",
        "is so close to snapping",
        "woke up and chose violence",
        "has already snapped",
        "has a cool hat",
        "lies about their age",
        "needs therapy",
        "got their ears pierced at Claire's",
        "wants to go to Applebee's",
        "is banned from Applebee's",
        "is so hungover",
        "has a headache",
        "can be real dick",
        "has had their medical license revoked",
        "is currently facing a lawsuit",
        "denies any and all responsibility for... the incident",
        "thinks your mom is hot",
        "thinks your dad is hot",
        "thinks your parent (of unspecified gender) is hot",
        "woke up in the wrong genre",
        "is from the LARP equivalent of Texas",
        "has blue hair and pronouns",
        "won't shut up about their kids",
        "drives a minivan",
        "has got it going on",
        "is really good at not throwing up",
        "who remembers the 21st night of September"
    ]
}

function randomString(arr) {
    const randomIndex = Math.floor(Math.random() * arr.length);
    const item = arr[randomIndex];
    return item;
}

function npcGen() {
    const charA = randomString(npcElements.charType);
    const traitA = randomString(npcElements.trait);
    const charB = randomString(npcElements.charType);
    const traitB = randomString(npcElements.trait);
    const charC = randomString(npcElements.charType);
    const traitC = randomString(npcElements.trait);

    document.getElementById("charVarA").innerHTML = charA;
    document.getElementById("traitVarA").innerHTML = traitA;
    document.getElementById("charVarB").innerHTML = charB;
    document.getElementById("traitVarB").innerHTML = traitB;
    document.getElementById("charVarC").innerHTML = charC;
    document.getElementById("traitVarC").innerHTML = traitC;
}