const npcElements = {
    charType: [
        "a peasant girl",
        "a warrior",
        "a mage",
        "a lad",
        "a fruit-seller",
        "a sellsword",
        "a nomad",
        "a lord",
        "a knight",
        "an assassin",
        "a gentleman thief",
        "a soldier",
        "an empress",
        "a monk",
        "a ranger",
        "a rogue",
        "a ruffian",
        "a blacksmith",
        "a sorceror",
        "a witch",
        "an outlaw",
        "a woodsman",
        "a warlord",
        "a noblewoman",
        "a monsterologist",
        "a gentlewoman thief",
        "a druid",
        "a bard",
        "a young boy",
        "a swordmaster",
        "an apprentice",
        "an assassin-in-training",
        "a page",
        "a troubadour",
        "an enchantress-in-training",
        "an ogre",
        "a summoner-in-training",
        "a brigand",
        "a sorceror",
        "a dragon",
        "an elven prince",
        "a witch-in-training",
        "a centaur",
        "a charlatan",
        "a necromancer-in-training",
        "an enchanter",
        "a goblin",
        "a vampire",
        "a genie",
        "a shaman",
        "a prophet-in-training",
        "a sorceror-in-training",
        "a troll",
        "a pickpocket",

        "an eccentric candyman",
        "a coalescer",
        "an excavator",
        "a harvester",
        "a logger",
        "a skinner",
        "a farmer",
        "a hunter",
        "a lumberjack",
        "a miner",
        "a panner",
        "a butcher",
        "a carpenter",
        "a gemcutter",
        "a glassmaker",
        "a papermaker",
        "a smelter",
        "a tanner",
        "a weaver",
        "an architect",
        "a blacksmith",
        "a brewer",
        "a chef",
        "a glassblower",
        "a lapidary",
        "a leatherworker",
        "a tailor",
        "a trapmaker",
        "a woodworker",
        "an appraiser",
        "a laborer",
        "a mender"
    ],
    trait: [
        "can be restless",
        "can be ambitious",
        "is kind",
        "used to be idealistic",
        "is past prime",
        "can be brusque",
        "is stubborn to a fault",
        "has not laughed in a long time",
        "lies more often than not",
        "is surprisingly gentle",
        "once was hopeful",
        "can be independently-minded",
        "can be selfish",
        "can be sharp",
        "can be over-critical",
        "tends to be reckless",
        "is abrasive",
        "has become aimless",
        "has a lot of defense mechanisms",
        "can be cold",
        "has a tendency to be cowardly",
        "is destructive",
        "can be detached",
        "can be judgemental",
        "has a sense of humor",
        "has a reputation for being melodramatic",
        "has burnt every bridge",
        "can be vain",
        "has become withdrawn",
        "is taciturn",
        "can be stoic",
        "is suave",
        "is quick-witted",
        "no longer has any loyalties",
        "has a strong moral compass",
        "has 99 problems, and a sidekick is one of them",
        "is a crank",
        "has a reputation for being eccentric",
        "is misunderstood",
        "is a worrywart",
        "is innocent",
        "is rather unpredictable",
        "is unexpectedly charismatic",
        "has a poker face",
        "is soft-hearted",
        "can be independently-minded",
        "used to be selfish",
        "has many controversial opinions",
        "is deadpan",
        "can be pretentious",
        "is prim",
        "is puritanical",
        "can be tactless",
        "tends to attract trouble",
        "is blind",
        "thrives on drama",
        "can be forgetful",
        "is a drifter",
        "is a chatterbox",
        "is spineless",
        "is rather incompetent",
        "is bright",
        "is sensible to a fault",
        "is a forgiving soul",
        "is braver than most",
        "has no moral code",
        "has run away",
        "is affable",
        "is taciturn",
        "is overly polite",
        "can be naïve",
        "can be overly pompous",
        "is overly adventurous",
        "is a lover of books" 
    ]
}

function randomString(arr) {
    const randomIndex = Math.floor(Math.random() * arr.length);
    const item = arr[randomIndex];
    return item;
}

function npcGen() {
    const character = randomString(npcElements.charType);
    const trait = randomString(npcElements.trait);

    document.getElementById("charVar").innerHTML = character;
    document.getElementById("traitVar").innerHTML = trait;
}